// Frontend/src/components/Pages/BooksDetails/BookDetails.tsx
import { Component, ReactNode } from "react";
import { Link, RouteComponentProps, withRouter } from "react-router-dom";
import { Book } from "../../../assets/models/favoriteBooks.models";
import { BookQuotes } from "./BookQuotes";
import { bookService } from "../../../services/book.service";
import { connect } from "react-redux";
import { RootState } from "../../../../store/store";
import { User } from "../../../assets/models/user.model";
import { favService } from "../../../services/fav.service";

interface Params {
  id: string;
}
interface BookDetailsProps extends RouteComponentProps<Params> {
  user: User | null;
}
interface BookDetailsState {
  book?: Book | null;
  isFavorite: boolean;
}

class _bookDetails extends Component<BookDetailsProps, BookDetailsState> {
  componentDidMount(): void {
    this.fetchBook();
    this.checkIfInFav();
  }

  private id = this.props.match.params.id;

  async fetchBook() {
    const book = await bookService.getBookById(this.id);
    this.setState({
      book,
    });
  }

  onAddToFavorites = async () => {
    if (!this.props.user) {
      this.props.history.push("/login");
    } else {
      try {
        if (this.state.isFavorite) {
          await favService.deleteFromFavorite(this.id);
          this.setState({ isFavorite: false });
        } else {
          const book = await favService.addToFavorite(
            this.props.match.params.id
          );
          if (book) {
            this.setState({ isFavorite: true });
          }
        }
      } catch (err) {
        console.log(err);
      }
    }
  };

  checkIfInFav = async () => {
    const boolean = await favService.ifBookInFav(this.id);
    this.setState({ isFavorite: boolean });
  };

  render(): ReactNode {
    var book;
    if (this.state?.book) {
      book = this.state.book;
    }
    const langName = new Intl.DisplayNames(["en"], {
      type: "language",
    });
    return (
      <section>
        {book ? (
          <>
            <header>
              <img src={book?.cover} />
              <section className="details">
                <h1>{book?.title}</h1>
                {
                  <section className="authors">
                    <h2 className="title"> Authors:</h2>
                    <div className="names">
                      {book?.authors.map((author) => (
                        <p key={author.name}>{author.name}</p>
                      ))}
                    </div>
                  </section>
                }
                {!!book?.languages.length && (
                  <section className="languages">
                    <h2 className="title">Language:</h2>
                    {/* Each book has only one language, stored in an array, so no need to use map */}
                    <p>{langName.of(book?.languages[0])}</p>
                  </section>
                )}
                {!!book?.subjects?.length && (
                  <section className="subjects">
                    <h2 className="title">Subjects:</h2>
                    <ul>
                      {book?.subjects.length === 1
                        ? book.subjects[0]
                        : book.subjects.map((subject) => subject).join(", ")}
                    </ul>
                  </section>
                )}
                {book.download_count && (
                  <section className="downloads">
                    <h2 className="title">Downloads:</h2>
                    <p>{book?.download_count}</p>
                  </section>
                )}
              </section>
              <section>
                <button onClick={this.onAddToFavorites}>
                  {this.state.isFavorite
                    ? "Delete from favorite"
                    : "Add to favorites"}
                </button>{" "}
                <Link to={`/${book.id}/txt`}>Read</Link>
              </section>
            </header>
            <main>
              <BookQuotes />
            </main>
          </>
        ) : (
          <p>Loading...</p>
        )}
      </section>
    );
  }
}
const mapStateToProp = (state: RootState) => ({
  user: state.userModule.user,
});
export const BookDetails = connect(mapStateToProp)(withRouter(_bookDetails));

// Angular Frontend/src/app/cmps/books-components/book-details/book-details.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { Book } from '../../../models/book/book.model';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute } from '@angular/router';
import { map, Subscription } from 'rxjs';
import { UserService } from '../../../services/user/user.service';
import { User } from '../../../models/user/user.model';
import { BooksService } from '../../../services/books/books.service';

@Component({
  selector: 'book-details',
  standalone: false,

  templateUrl: './book-details.component.html',
  styleUrl: './book-details.component.scss',
})
export class BookDetailsComponent implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute);
  public langName = new Intl.DisplayNames(['en'], { type: 'language' });
  book_ = toSignal<Book>(this.route.data.pipe(map((data) => data['book'])));
  private subscription: Subscription | null = null;
  private userService = inject(UserService);
  private bookService = inject(BooksService);
  public user: User | null = null;
  public isAdded: boolean = false;
  ngOnInit(): void {
    this.subscription = this.userService.login().subscribe((user) => {
      this.user = user;
    });

    this.bookService.getMyFavBooks().subscribe((ans: any) => {
      const bookId = this.book_()?.id;
      this.isAdded = ans.books.some((book: any) => book.id === bookId);
    });
  }

  onAddToFavorites = async () => {
    const book = this.book_();
    if (book && !this.isAdded) {
      this.isAdded = true;
      this.bookService.addBookToFav(book.id).subscribe();
    } else if (book && this.isAdded) {
      this.isAdded = false;
      this.bookService.removeFromFav(book.id).subscribe();
    }
  };

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }
}

<section *ngIf="book_() as book" class="book-preview">
  <header>
    <img [src]="book.cover" />
    <section class="details">
      <h1>{{ book.title }}</h1>
      <section *ngIf="!!book.authors.length">
        <h2 class="title">Authors:</h2>
        <div class="names">
          <p *ngFor="let author of book.authors">{{ author.name }}</p>
        </div>
      </section>
      <section *ngIf="!!book.languages.length" class="languages">
        <h2 class="title">Languages:</h2>
        <p>{{ langName.of(book.languages[0]) }}</p>
      </section>
      <section class="downloads" *ngIf="book.download_count as downloads">
        <h2 class="title">Downloads:</h2>
        <p>{{ downloads }}</p>
      </section>
      <section class="btns">
        <button *ngIf="user" (click)="onAddToFavorites()">
          {{isAdded?"Remove from":'Add to'}} favorites
        </button>
        <a [routerLink]="['/book', book.id, 'txt']">Read</a>
      </section>
    </section>
  </header>
  <main>
    <books-quotes [bookId]="book.id" />
  </main>
</section>
