// Angular Frontend/src/app/cmps/header/header.component.ts
import { Component } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import { UserService } from '../../services/user/user.service';
import { User } from '../../models/user/user.model';
@Component({
  selector: 'app-header',
  standalone: false,
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  // Define links as a class property
  public user: User | null = null;
  public links: Array<{
    title: string;
    to?: string;
    hidden?: boolean;
    onClick?: (e: Event) => void;
  }> = [];

  public hidden: boolean = false;

  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer,
    private userService: UserService
  ) {
    this.matIconRegistry.addSvgIcon(
      'logo',
      this.domSanitizer.bypassSecurityTrustResourceUrl('assets/logo.svg')
    );
    this.userService.login().subscribe({
      next: (user) => {
        this.user = user;
        this.updateLinks();
      },
      error: (err) => {
        console.log(err);
      },
    });
    this.updateLinks();
  }
  private updateLinks() {
    this.links = [
      { title: 'Profile', to: '/profile', hidden: !this.user },
      { title: 'Login', to: '/login', hidden: !!this.user },
      {
        title: 'Sign out',
        hidden: !!this.user,
        onClick: async (e: Event) => {
          e.preventDefault();
          await this.userService.logout();
          this.user = null;
          this.updateLinks();
        },
      },
    ];
  }
}

<section class="header">
  <main class="header-main">
    <a routerLink="" class="logo">
      <mat-icon svgIcon="logo"></mat-icon>
      <h1>MyBook</h1>
    </a>
    <nav class="navigation">
      <ul class="list">
        <ng-container *ngFor="let link of links">
          <!-- Render as a router link if "to" is defined -->
          <a
            *ngIf="link.to && link.hidden !== true; else clickLink"
            [routerLink]="link.to"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
          >
            {{ link.title }}
          </a>
          <!-- Render as a button if "onClick" is defined -->
          <ng-template #clickLink>
            <a
              *ngIf="link.onClick && link.hidden"
              (click)="link.onClick($event)"
            >
              {{ link.title }}
            </a>
          </ng-template>
        </ng-container>
      </ul>
    </nav>
  </main>
</section>

// Frontend/src/components/Header.tsx
import { Component, ReactNode } from "react";
import { Link } from "react-router-dom";
import { ReactSVG } from "react-svg";
import logo from "/imgs/logo.svg";
import { connect } from "react-redux";
import { RootState } from "../../store/store";
import { User } from "../assets/models/user.model";
import { userService } from "../services/user.service";

interface HeaderProps {
  user: User | null;
}

export class _Header extends Component<HeaderProps> {
  get getLinks() {
    const { user } = this.props;
    return [
      { title: "Home", to: "/" },
      { title: "Profile", to: "/profile", hidden: !user },
      { title: "Login", to: "/login", hidden: user },
      {
        title: "Sign out",
        to: "",
        hidden: !user,
        onClick: async (e: React.MouseEvent<HTMLAnchorElement>) => {
          e.preventDefault();
          userService.logout();
        },
      },
    ].map(
      (link) =>
        !link.hidden && (
          <li key={link.to}>
            <Link to={link.to} onClick={link.onClick || undefined}>
              {link.title}
            </Link>
          </li>
        )
    );
  }
  render(): ReactNode {
    return (
      <section className="header">
        <main className="header-main">
          <Link to={"/"} className="logo">
            <ReactSVG src={logo} />
            <h1>MyBook</h1>
          </Link>
          <nav className="navigation">
            <ul className="list">{this.getLinks}</ul>
          </nav>
        </main>
      </section>
    );
  }
}
const mapStateToProp = (state: RootState) => ({
  user: state.userModule.user,
});

export const Header = connect(mapStateToProp)(_Header);
