// Frontend/src/components/Header.tsx
import { Component } from "react";
import { Link } from "react-router-dom";
import { ReactSVG } from "react-svg";
import logo from "/imgs/logo.svg";
import { connect } from "react-redux";
import { RootState } from "../../store/store";
import { User } from "../assets/models/user.model";

interface HeaderProps {
  user: User | null;
}

export class _Header extends Component<HeaderProps> {
  links = [
    { title: "Home", to: "/" },
    { title: "Profile", to: "/profile", hidden: !this.props.user },
    { title: "Login", to: "/login", hidden: this.props.user },
    { title: "Sign out", to: "/logout", hidden: !this.props.user },
  ];
  render() {
    return (
      <section className="header">
        <main className="header-main">
          <Link to={"/"} className="logo">
            <ReactSVG src={logo} />
            <h1>MyBook</h1>
          </Link>
          <nav className="navigation">
            <ul className="list">
              {this.links.map(
                (link) =>
                  !link.hidden && (
                    <li key={link.to}>
                      <Link to={link.to}>{link.title}</Link>
                    </li>
                  )
              )}
            </ul>
          </nav>
        </main>
      </section>
    );
  }
}
const mapStateToProp = (state: RootState) => ({
  user: state.userModule.user,
});

export const Header = connect(mapStateToProp)(_Header);

// Angular Frontend/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: false,
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'], // Fixed the property name
})
export class HeaderComponent {
  // Define links as a class property
  links = [
    { title: 'Profile', to: '/profile' },
    { title: 'Login', to: '/login' },
    {
      title: 'Sign out',
      to: '',
      onClick: async (e: Event) => {
        e.preventDefault();
        // Replace `userService.logout()` with actual implementation
        console.log('Logged out');
      },
    },
  ];

  
}

<section class="header">
  <main class="header-main">
    <a routerLink="" class="logo">
      <span>
        <svg-icon src="img/logo.svg"></svg-icon>
      </span>
      <h1>MyBook</h1>
    </a>
    <nav class="navigation">
      <ul class="list">
        <a
          *ngFor="let link of links"
          [routerLink]="link.to"
          routerLinkActive="active"
          [routerLinkActiveOptions]="{ exact: true }"
          >{{ link.title }}</a
        >
      </ul>
    </nav>
  </main>
</section>
